<?php

declare(strict_types=1);

namespace MHMRentiva\Tests\Gates;

use WP_UnitTestCase;

/**
 * changelog-tr.json is Turkish that customers read, so it is spelled in Turkish.
 *
 * The About screen's Support tab loads this file for a Turkish admin and renders it
 * (SupportTab.php picks changelog-tr.json by locale, falling back to the English one).
 * It ships inside the plugin package. It is not an internal note.
 *
 * On 2026-08-29 the 6.1.3 entry went out ASCII-folded -- "6.1.2 oncesinde
 * yapilandirilmis sitelerde arac galerileri artik kaybolmuyor" -- while every entry
 * around it was written properly. It reached the WordPress.org directory that way.
 * The cause was mundane: the entry was generated by a script whose author avoided
 * non-ASCII to dodge an encoding problem, and no gate looked at the result.
 *
 * The check is deliberately narrow. It does not try to detect Turkish generally; it
 * asserts that the three category words this file's own voice uses -- Düzeltildi,
 * Güvenlik, Değişti -- are spelled with their diacritics, and that a handful of
 * unambiguous folded forms never appear. A broader "does this look Turkish" test would
 * be a guess; these are strings we write ourselves, in a shape we control.
 *
 * WHAT THIS DOES NOT COVER: changelog.json (English by design), readme.txt, and any
 * Turkish written outside these two shapes. A folded word this list does not name will
 * pass. Add it here when it bites rather than widening the test into a language model.
 */
final class TurkishChangelogOrthographyTest extends WP_UnitTestCase
{
    /**
     * Folded spellings that are never correct in Turkish prose we author.
     *
     * Each maps to what it should be, so a failure tells the writer the fix instead of
     * only naming the offence.
     *
     * @var array<string,string>
     */
    private const FOLDED = array(
        'Duzeltildi' => 'Düzeltildi',
        'Guvenlik'   => 'Güvenlik',
        'Degisti'    => 'Değişti',
        'Eklendi:'   => 'Eklendi:',   // already correct; kept so the list reads as the full vocabulary
        'oncesinde'  => 'öncesinde',
        'yapilandir' => 'yapılandır',
        'galerileri' => 'galerileri', // correct as-is; the folded neighbours above carry the case
        'arac '      => 'araç ',
        'guncelle'   => 'güncelle',
        'gorsel'     => 'görsel',
        'hala '      => 'hâlâ ',
    );

    public function test_the_turkish_changelog_is_written_in_turkish(): void
    {
        $path = dirname(__DIR__, 2) . '/changelog-tr.json';
        $raw  = file_get_contents($path);

        $this->assertNotFalse($raw, 'changelog-tr.json is missing. It ships in the package and the About screen reads it.');

        $entries = json_decode((string) $raw, true);
        $this->assertIsArray($entries, 'changelog-tr.json is not valid JSON, so the About screen would fall back to English silently.');
        $this->assertNotEmpty($entries, 'changelog-tr.json is empty; this gate would measure nothing.');

        // Prove the slice is real before trusting it: the newest entry must be the
        // version being shipped, otherwise the file is stale and its spelling is beside
        // the point.
        $this->assertSame(
            MHMRENTIVA_VERSION,
            $entries[0]['version'] ?? '',
            'The newest changelog-tr.json entry is not the version in the plugin header. '
            . 'A release that forgot its Turkish changelog entry fails here rather than on '
            . 'a customer screen.'
        );

        $offences = array();
        foreach ($entries as $entry) {
            $text = $entry['title'] . ' ' . implode(' ', (array) ($entry['changes'] ?? array()));
            foreach (self::FOLDED as $folded => $correct) {
                if ($folded === $correct) {
                    continue;
                }
                if (false !== mb_stripos($text, $folded)) {
                    $offences[] = sprintf('%s: "%s" should be "%s"', $entry['version'], $folded, $correct);
                }
            }
        }

        $this->assertSame(
            array(),
            $offences,
            "changelog-tr.json contains ASCII-folded Turkish. Customers read this file on the "
            . "About screen:\n  " . implode("\n  ", $offences)
        );
    }
}
